[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run db:generate && npm run build"

[deploy]
startCommand = "npm run db:deploy && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
